### ISSUE TITLE
Send build comments and tags in hook payload

### ISSUE THREAD

**Issue by ssube** [tcplugins/tcWebHooks#12]
I'd like to use webhooks to integrate gitlab and teamcity, using the comments field to link the two (create a merge, run a build, comment on the merge). It doesn't look like the comments are being sent with the latest stable build. I'm looking for a workaround, but it would be nice to get that extra info.

**Comment by netwolfuk** [comment]
I presume you want the commit message from the VCS when running a build as a result of a merge?

TeamCity has two concepts of comment. The one above (the commit message) and also a comment on a build. However, the later tends to be commenting on builds that have already finished, so not much use to us while a build is running (since it's unlikely that comments will exist at that point in time).

So by default I presume build commit message is the one you are referring to. 
Commit messages are against a VCS (a build can use multiple VCSs) and against a commit. A build could consist of multiple commits, especially if it hasn't succeeded in a while. Should all commits since the last successful build be counted as contributing comments?
Also, what about a build that is triggered by a user? There may be no commits since the last build.

I'm interested in some more information about your use case. Thanks.

**Comment by netwolfuk** [comment]
I just noticed that you can add a comment when triggering a build (clicking the ellipse on the run button). Is that the comment you were referring to? If so, that should be easy to add into the payload for referencing in a webhook.

**Comment by ssube** [comment]
Yep, I was talking about the initial comment. I wasn't aware you could leave comments after the fact, so comments might not be the best solution.

My goal is to allow developers (or our Huginn server) to kick off a build and mention some merge request or issue in the comment, which I see in the hook and comment on the reference. That would work with a parameter or comments, but comments sound like they might be the better choice.

**Comment by netwolfuk** [comment]
@ssube Here is a first go at adding comments and tags to the webhook payload. From my limited testing it's good. I've tested the NameValue pairs and JSON payload formats.
I've not added commit messages yet. You can download a build from here: https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/583389:id/tcWebHooksPlugin-0.9.43.73.zip
Just login as guest if you're prompted.

**Comment by netwolfuk** [comment]
Closing. This was all added in commit a8bbbcdd7b08070571a1717bfc884714104f521b
