### ISSUE TITLE
Edit Webhook UI not working

### ISSUE THREAD

**Issue by skakraze5** [tcplugins/tcWebHooks#123]
## Expected Behavior
The ability to edit a webhook

## Current Behavior
The window/UI that opens up does not appear to work or load correctly

![](https://content.screencast.com/users/skakraze/folders/Snagit/media/31ba5a50-7e80-4e93-9f9a-f5373040b993/2018-11-30_18-24-08.png)

## Steps to Reproduce (for bugs)
1. Webhooks -> Add Project Webhooks -> Edit Webhook
2. Incomplete UI pops up... (see pic above)

## Your Environment

* tcWebHooks Version: 1.1-alpha18.241.356
* TeamCity Version: TeamCity Enterprise 2018.1.4 (build 58724)
* TeamCity server Operating System: windows server 2016
* Are you using a WebHook Template?: Custom Flowdock Template

**Comment by skakraze5** [comment]
FWIW, this was working before. We recently updated TeamCity so it could be related to switching to 2018.1.4 . Just a hunch though. At some point I'll try updating the plugin to the stable release.

**Comment by netwolfuk** [comment]
Thanks for raising this @skakraze5.
I can reproduce this on the latest 2018.2 RC1, and also on 2018.1.4

It looks like it could be a CSS change, but I've not tracked it down yet.

**Comment by netwolfuk** [comment]
Due to a change in Teamcity versions 2018.1.4 and 2018.2 RC, the
WebHookDialog, which extends BS.AbstractModalDialog, was no longer
setting the height correctly.

The JS code would run as part of ShowDialog, and once the dialog is
displayed, would read the height of the last tab and then set the height
of all other tabs to match. This resulted in the tabs all being uniform
height, so the dialog height would remain constant between tabs.

However, with the recent change in teamcity, the dialog was not actually
visible, so the measure phase returned 0. This set the height of the
tabs within the webhook dialog to 0px, and resulted in the text
overlfowing off the bottom of the dialog box.

The actual code to make the dialog visible must be being run after the
ShowDialog method completes now. It's being bound to the ShowDialog
finish event from what I can tell.

The workaround is to use CSS to set the min-height of the four tabs, and
remove the JS code.

**Comment by netwolfuk** [comment]
Version v1.1.261.385 released

**Comment by skakraze5** [comment]
👍 Awesome! Thanks for looking into this. Sorry I didn't reply sooner. I was out for long the weekend. Just now catching up on emails. But looks like you tracked it down. Nice work.
