### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by nrukavkov** [tcplugins/tcWebHooks#158]
Hello. When are u gonna release a version 1.2?

**Comment by netwolfuk** [comment]
Hi @nrukavkov   At the moment I get only a few hours a week to work on it. So, it's taking a while unfortunately. 
[These are the items left before release on milestone 1.2. ](https://github.com/tcplugins/tcWebHooks/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.2+-label%3A%22waiting+for+release%22)
Are you waiting for something specific?

**Comment by netwolfuk** [comment]
Down to five issues left now. Maybe you could try a 1.2 version and do some testing?

**Comment by nrukavkov** [comment]
> Hi @nrukavkov At the moment I get only a few hours a week to work on it. So, it's taking a while unfortunately.
> [These are the items left before release on milestone 1.2. ](https://github.com/tcplugins/tcWebHooks/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.2+-label%3A%22waiting+for+release%22)
> Are you waiting for something specific?

Hi. Yeah, we are waiting a callback event 'added to queue'

**Comment by netwolfuk** [comment]
Oh right. That was quite complicated. I don't think I'd be able to back port that to 1.1

You're more than welcome to try an alpha release. They are very stable.

**Comment by nrukavkov** [comment]
> Oh right. That was quite complicated. I don't think I'd be able to back port that to 1.1
> 
> You're more than welcome to try an alpha release. They are very stable.

Is it possible to rollback from 1.2 to 1.1 if something is going wrong? I mean without a setting up it like a new installation. Or it would be better to backup some config files?

**Comment by netwolfuk** [comment]
> Is it possible to rollback from 1.2 to 1.1 if something is going wrong?

There are some changes that modify the config files, so I would recommend backing up the files in `$BuildServer/config/projects/*/pluginData/plugin-settings.xml*` (there is one per project)
and also 
`$BuildServer/config/webhook-templates.xml` (which might or might not exist depending on whether there are any locally edited templates) 

I'll do a test too, but it might take me a few days to get a chance. If there are any big issues, I'll look at trying fix them and do a release of 1.1 so that rollback is seamless.

The one thing I can remember that will cause an issue is the removal of the `format` attribute in a webhook.
```
<webhook url="http://somerthing" format="jsontemplate" template="flowdock">
```
becomes
```
<webhook url="http://somerthing" template="flowdock">
```
This is because template is unique, and a template knows its format, so the information is redundant. It also constrains templates from being able to change format. Rolling back to 1.1 would cause an issue there.  For more info see a9df17bb0f9cb94a93103f8ff3b2cbc418f9a11e

**Comment by netwolfuk** [comment]
Hi @nrukavkov  I spent some time over the weekend and added support for rolling back from 1.2 to 1.1.  I will release a new 1.1 version shortly.

All the webhooks and templates remain for the formats which are only supported by 1.2, but when they execute, they log an error that there is no template found. However, when you dicide to upgrade to 1.2 again the future, they will all start working again.

The log looks like this...

![image](https://user-images.githubusercontent.com/88687/84017224-78045e80-a9d2-11ea-9c67-bf9dc11469a9.png)

Template test-01 is a valid template in 1.1 and returns a 204 status (good). The other three are not valid, so the webhooks created in 1.2 and associated with those new template types just fail to find the template and log that 901 error.

I believe this means upgrading and trying 1.2 is risk free. If you decide to rollback to 1.1, only newly created templates which use a new template format will stop working. The format from 1.1 is called "jsonTemplate", and anything of this format will just continue to work in 1.1 after rollback.

**Comment by nrukavkov** [comment]
Hello @netwolfuk. I've installed 1.2 alpha version. At first glance, everything works fine. Thank you. Later we will try to use 'added to queue' event in our software and let you know how it works.

**Comment by netwolfuk** [comment]
Great. Thanks for the update @nrukavkov.
I'll close this ticket.
