### ISSUE TITLE
Existing plugin-settings are not loaded when plugin is installed

### ISSUE THREAD

**Issue by netwolfuk** [tcplugins/tcWebHooks#167]
## Expected Behavior
Existing webhooks should be converted to work in 1.2.0
Possibly related to using VCS storage of settings.

## Current Behavior
Webhook settings are blank after upgrade

## Steps to Reproduce (for bugs)
1. Install 1.1.362.398
1. Create one webhhok in subproject. Set to single build and no subprojects.
1. Enable VCS storage of project settings.
1. Upgrade to 1.2.0
1. Webhooks blank on config page.

## Your Environment
* tcWebHooks Version: 1.1.362.398
* TeamCity Version: 2020.1.3
* TeamCity server Operating System:ubuntu
* Are you using a WebHook Template?: n/a

## Example Configuration (xml)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <webhooks enabled="true">
    <webhook url="https://rest-api-team-XYZ" enabled="true" format="json" template="none">
      <states>
        <state type="buildFixed" enabled="false" />
        <state type="changesLoaded" enabled="false" />
        <state type="responsibilityChanged" enabled="false" />
        <state type="buildFinished" enabled="true" />
        <state type="buildStarted" enabled="true" />
        <state type="buildFailed" enabled="true" />
        <state type="beforeBuildFinish" enabled="false" />
        <state type="buildSuccessful" enabled="true" />
        <state type="buildBroken" enabled="false" />
        <state type="buildInterrupted" enabled="true" />
      </states>
      <build-types enabled-for-all="false" enabled-for-subprojects="false">
        <build-type id="bt23" />
      </build-types>
    </webhook>
  </webhooks>
</settings>
```

**Comment by schernov-xo** [comment]
If you cannot reproduce it, I can reinstall old version, reset hooks and try to migrate one more time.

**Comment by netwolfuk** [comment]
If you get a chance to try the upgrade again, I would really appreciate it. You're lucky that you have the full history, so can roll back to a working version of 1.1 config and then took forward again to test it.

As I mentioned on the other ticket. I might not get a chance to get back to this until 1 or 2 days from now.

**Comment by schernov-xo** [comment]
I can reproduce it. It seems that it's an issue about a mix of git stored settings and either database store or ignored files. Let me explain in step-by-step:
TeamCity 2020.1.4 (docker)
Scenario:
* Install 1.2.0 and set up webhooks for projects A and B (not Root). Format: Legacy JSON, no special settings like template or auth.
* Check that everything is fine
* Disable plugin, restart IDEA, delete the plugin
* Install Old 1.1.362 and enable it, no reboot
* Go To Settings A (note: not B), there is no webhook (expected, as it is about forward compatibility)
* Set up web hook for A, you'll have changeset in git like (resetting to old format):
![Screen Shot 2020-09-14 at 12 31 41](https://user-images.githubusercontent.com/41187778/93069418-4d3b3d80-f686-11ea-9c4c-2e7fb827281d.png)
* Check Notifications on Project A - it works
* Check Notifications on Project B - does not work (expected); do not change the webhook config
* Disable the plugin, reboot TeamCity, delete the plugin, install 1.2.0, enable it
* ATTENTION 1: Go to Project A - there is no webhook settings (not expected):
![Screen Shot 2020-09-14 at 12 10 47](https://user-images.githubusercontent.com/41187778/93069623-9095ac00-f686-11ea-884b-f0798e86148d.png)
* Add a webhook, it is working fine, in git log you can see
![Screen Shot 2020-09-14 at 12 35 46](https://user-images.githubusercontent.com/41187778/93069950-f124e900-f686-11ea-8071-9a63d5dd4560.png)
* ATTENTION 2: Project B; reminder: the plugin descriptor should be stored in format 1.2.0 (because we did not rewrite it with 1.1.362). The webhooks list is also empty (not expected).
* And the most interesting: add webhook for project B with exactly the same settings. The webhook is here, it is working fine, it is restored on TeamCity reboot. BUT: there is no commit in git log (because there is no configuration change). I assume there is at least one more place that stores the configuration, and it is out of this git-related storage.

Hope this instruction is clear enough.

**Comment by netwolfuk** [comment]
Thank you, thank you, thank you! These steps are amazing! 

A couple of clarifications:
1. I presume step 3 is "restart Teamcity", not "restart IDEA".
2. 1.1.374 should allow downgrading of 1.2.0 to 1.1. But that is not what we're trying to test here.

The gold is in the discovery that the file exists with no change, but is not loaded. 
I'm guessing it's some race condition somewhere in the code that handles the updates to <-> from GIT.

There are a few states/events that I need to test better.
1. Creating a webhook happens in memory in TeamCity.
2. TeamCity should then write that to disk when persist is called. This is the code that changed to now include the "comments"
3. TeamCity tells my plugin that file could have changed in GIT. For example, you make a change in GIT, and the file is discovered by TeamCity and loaded into memory.

I believe that last stage is required to be handled by my plugin code. I suspect I am not doing that.
I think I probably need some code like this...
https://github.com/tcplugins/tcChatBot/blob/71b9f518176f7130013c17f61e40822aee242353/tcChatBot-server/src/main/java/chatbot/teamcity/settings/project/ChatClientConfigStorage.java#L37-L51

This has given me some really useful information. Thank you so much for taking the time to test it.

**Comment by schernov-xo** [comment]
1. sure, TeamCity, not IDEA

Just to be clear: I never make changes to git directly, I only change TeamCity settings via UI, it flushes it to git storage. Git is just a reserve for fast restore in case of service destruction and a convenient log to watch the changes.


No problem, let me know if you need more information or checking hypothesis.

**Comment by netwolfuk** [comment]
Ah yes. Thanks for the clarification.
My suspicion is that any recent 1.2 will have this issue. I don't think it's related to the comments.

1.2 has a cache of webhooks. This is probably where to bug has crept in.

The cache is what powers `/webhooks/search.html?show=all` and the other search functions.

**Comment by netwolfuk** [comment]
Hi @schernov-xo   I am able to reproduce the behaviour, simply by installing the plugin without a restart.
Once restarted, all the previous webhooks are found.

So, it's something that happens at startup in the plugin, but not when the plugin is enabled whilst the server is already running.
It probably happens in 1.1 too. This appears to be consistent with what you found above.

**Comment by netwolfuk** [comment]
The workaround is to install the new plugin version and then restart TeamCity. In that case, the settings load correctly.

I have raised a bug in the TeamCity bug tracker, but using plugin-settings.xml is the old way of storing settings, so they might not fix it quickly.

**Comment by netwolfuk** [comment]
https://youtrack.jetbrains.com/issue/TW-67777

I'm going to close this ticket here on GitHub. I don't think there is anything I can do to resolve this.
