### ISSUE TITLE
Dependent projects Parameters

### ISSUE THREAD

**Issue by Peterosh** [tcplugins/tcWebHooks#197]
Hello. How do I get the parameters of dependent projects .for example ${dep. *. Build. VCS. Number}

**Comment by netwolfuk** [comment]
Hi @Peterosh 

Which version of tcWebHooks are you running?
Which template engine is your template using? Standard or Velocity.

For standard, I think I convert all the dotted names to with an underscore instead. Eg, `${dep_mybuild_Build_VCS_Number}`.

For Velocity I'd need to check, but I'm pretty sure they're there too somehow.

**Comment by Peterosh** [comment]
Tcwebhook version is 1.1.374.403
I used a custom template.
Can I use a wildcard?
Such as ${dep_ * _Build_VCS_Number}
I've tried. He's not working

**Comment by netwolfuk** [comment]
It's not possible to use a wildcard sorry.
What are you wanting to achieve? I might be able to give you some other suggestions.

**Comment by Peterosh** [comment]
I want to use a set of templates for all project notifications. 
But they dependent on different projects.
You know, different project dependencies, variables are different.
For example,
dep.pro1.build.vcs.number
dep.pro2.build.vcs.number
I want to use
dep.*.build.vcs.number

**Comment by netwolfuk** [comment]
I think if there is anything I can try it will be on a velocity template as we can loop over lists and use conditionals. 

I'll try some things over the weekend and come back to you.

**Comment by Peterosh** [comment]
Thank you very much

**Comment by netwolfuk** [comment]
Hi @Peterosh 

I've written an example template which uses Velocity logic to loop over the parameters on the build.
You will need to install one of the [1.2.0 alpha releases](https://github.com/tcplugins/tcWebHooks/releases), so that you can use the Velocity template engine with a template.

The parameters on my test build look like this in the Teamcity UI
![image](https://user-images.githubusercontent.com/88687/162552641-681de596-76a7-4ee3-bd95-cffd846d091e.png)

With Velocity, we have full programming access to the objects in a build. Here is an example of looping over the parameters of the `$build` object. 
```
#foreach ($paramEntry in $build.parametersProvider.all.entrySet())
#if ($paramEntry.key.startsWith("dep.") && $paramEntry.key.endsWith(".build.vcs.number") && !$paramEntry.key.endsWith(".system.build.vcs.number"))
${paramEntry.key} : ${paramEntry.value}
#end
#end
```

When I preview the template in the template editor, I can see the values being found and displayed.
![image](https://user-images.githubusercontent.com/88687/162552772-61ac42a8-a2d0-47ed-9df1-e17453e64c32.png)

**Comment by netwolfuk** [comment]
BTW, the `${build]` object in a Webhook Template is a TeamCity `SBuild` class.
You can therefore access any methods on the SBuild class as defined in the TeamCity javadocs for https://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/serverSide/SBuild.html

With Velocity, you can access an object item by name if the method starts with `get`, eg. `$build.parametersProvider` will call the method `getParametersProvider()`. If a method does not start with `get`, then you can still call it but you need to call the method name explicitly. For example the method above `entrySet()`.

**Comment by Peterosh** [comment]
Follow your steps to create templates and start reporting errors.
![image](https://user-images.githubusercontent.com/18716577/162933795-e494c5bb-c24d-44ed-ba3e-879680ff6895.png)

I just want to copy other templates or modify other templates. At this time, I will receive the following error
![image](https://user-images.githubusercontent.com/18716577/162934248-3676c7aa-8128-4c27-8849-ce8f3e8ce909.png)

I currently have no way to create a JSON Velocity Template
version:
![image](https://user-images.githubusercontent.com/18716577/162934879-485f4034-dc1f-40cb-bd8c-56068fbb5d06.png)

**Comment by netwolfuk** [comment]
Great. I'll close this issue
