### ISSUE TITLE
Investigate Mute or Fix Test callback

### ISSUE THREAD

**Issue by amadeuszpolak** [tcplugins/tcWebHooks#210]
Hi, 

I would like to mark a failed test as Fixed and get some callback to be able re run the build again. Is is possible via tcWebHooks ?

**Comment by netwolfuk** [comment]
Hi @amadeuszpolak. 

tcWebHooks does not currently support this. I see there is [a callback](https://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/serverSide/BuildServerListener.html#testsMuted(jetbrains.buildServer.serverSide.mute.MuteInfo)) that I can use to detect when tests are muted. I'm not sure if this works for "fixed" too.

I can see another on that page for "fixed tests", so I will try adding a dummy listener for the mute callback and see which events it fires on.

After that we can make a decision on whether we want to add a new build state for this to tcWebHooks.

**Comment by netwolfuk** [comment]
I've done some testing, and can see a way to subscribe to muted/unmuted tests, but not Mark as Fixed.
I have raised a ticket with TeamCity support to see if I have missed something.

https://youtrack.jetbrains.com/issue/TW-79828/Listen-for-Tests-Mark-as-fixed-event-in-OpenAPI

**Comment by amadeuszpolak** [comment]
That would be also great to have a callback from muted/unmuted tests. But have you seen this ? 

In Notification Rules section there is a option to subscribe to "Investigation is updated" option (inside Investigation there is a Fixed tests option), maybe this could be used ?

<img width="1251" alt="Screenshot 2023-02-20 at 08 32 48" src="https://user-images.githubusercontent.com/3585033/220041801-b1a0b009-93a7-43df-9f4f-c242ead04025.png">

**Comment by netwolfuk** [comment]
Hi @amadeuszpolak   The teamcity support team replied, and I am already listening for the responsibility changed event.

I have been able to trigger a build from marking the test as fixed. However, I found and fixed a bug that would sometimes stop ResponsibilityChanged from triggering.

Make sure you get the latest build from [here](https://teamcity.jetbrains.com/buildConfiguration/WebHooksAndOtherPlugins_TcWebHooks?buildTypeTab=overview&mode=builds). I just pushed the change, so the build  should run shortly.

Once that is installed, this is what I did...

1. Create a new template that looks like the payload to queue a build.
   ```
   {
	"buildType": {
    	"id": "${myBuildTypeId}"
	}
   }
   ```
2. Create a token so that your user can trigger a build. This is done in your Profile page.  To be extra cautious, just grant the token permission to `Run Build` for the project you're interested in.
3. Create  a WebHook Parameter in your Project called something like `triggerToken`, so that you can pass this to the webhook.
>  ![image](https://user-images.githubusercontent.com/88687/220072824-84bac76b-cb5c-4ef6-98bd-8107d2017b0b.png)

4. Create a WebHook to trigger on `Responsibility Changed` and choose your new template. Set the URL to be the teamcity server with `/app/rest/buildQueue`.
>  ![image](https://user-images.githubusercontent.com/88687/220073218-a0f42c4b-c0c8-4a88-85d9-d8a35b4d4ffe.png)
5. Set the webhook to fire on just the build you want.
>  ![image](https://user-images.githubusercontent.com/88687/220073605-6a482520-0aff-47cb-9241-aeb7765be96f.png)
6. Set the webhook to use bearer authentication, add the triggerToken and create a  Parameter for the build Id.
    Ignore the filter. I was trying to only trigger on as user interaction, but I have not got that filter working yet.
>  ![image](https://user-images.githubusercontent.com/88687/220074011-7f53520c-e1e9-41b2-9962-afcb8f0b0aa8.png)
7. Mark your Tests as fixed, and the build should be triggered. You should see it executing in the history page.

**Comment by netwolfuk** [comment]
BTW, the notification is a different mechanism to the one I am able to use. It's the same events, but they have slightly different names. In the notifier it's called `Investigation is Updated`, but in tcWebHooks it's called `Responsibility Changed` because that is the name of the event hook I listen for.

I have also added hooks for Test muting on my local branch (not pushed yet) and my callback is called However it doesn't do anything yet. There is quite a lot more work to create a new event and add it to all the templates/rest api/UI/configuration code so I don't have it working yet.

**Comment by netwolfuk** [comment]
Support for tests muted/unmuted added and released as version 1.2.2
https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.2
