### ISSUE TITLE
Password field is in plan text

### ISSUE THREAD

**Issue by alwaysharsha** [tcplugins/tcWebHooks#227]
## Expected Behavior
Password field shouldn't be exposed in plain text

## Current Behavior
Currently, the password field is in plain text
![image](https://github.com/tcplugins/tcWebHooks/assets/11633504/bed5993d-de8c-4d99-b197-18e8b5b31ba3)

## Steps to Reproduce (for bugs)
Refer screen above when providing the credentials in basic it is capturing the credentials in plain text

## Your Environment

* tcWebHooks Version: 1.2.2
* TeamCity Version: 2023.5.3
* TeamCity server Operating System: Windows Server 2016
* Are you using a WebHook Template?: Yes

**Comment by netwolfuk** [comment]
BTW, the webhook configuration is stored on the teamcity server un-encrypted (I can't change how that works). So any implied security by using a hidden field in the webhook edit dialog would be mis-leading. That is why is it a plain text box, so that it's obvious that it won't be stored securely.

Referencing a "secure" WebHook Parameter is the better option.

**Comment by netwolfuk** [comment]
I'm going to close this out. Using a secure WebHook Parameter is the way to resolve this.
