### ISSUE TITLE
TeamCity Webhook is removed if you are using versioned settings

### ISSUE THREAD

**Issue by Super8film87** [tcplugins/tcWebHooks#232]
## Expected Behavior
If I reload my teamcity configuration using versioned settings with Kotlin, I expect that I'm able to store it.

## Current Behavior
Currently, when I reload a project, it is displayed in the UI but it is no longer available and it causes a UI error.

## Steps to Reproduce (for bugs)

1. Create Project 
2. Create a Webhook
3. Use Versioned Settings
4. Use kotlin as Settings Format
5. check use settings from vcs 
6. Load porject settings from vcs
7. Webhook is gone

## Your Environment

* tcWebHooks Version: 1.2.5
* TeamCity Version: 2023.05.04 build 129421
* TeamCity server Operating System: 
* Are you using a WebHook Template?:

**Comment by netwolfuk** [comment]
I think this is related to #229  
I have some workarounds that I need to publish as a new release. 

The underlying problem is that changes to VCS config are not noticed by the tcWebHooks plugin. I have raised an issue with [Jetbrains](https://youtrack.jetbrains.com/issue/TW-84801/Listen-for-event-when-Project-is-edited-via-VCS-kotlin-or-xml)

**Comment by netwolfuk** [comment]
If you get a chance can you please test https://github.com/tcplugins/tcWebHooks/releases/tag/v2.0.1
I am pretty sure this will now be resolved.
