### ISSUE TITLE
${buildStatusHtml} in Tailored JSON format is not escaped, producing malformed JSON

### ISSUE THREAD

**Issue by sirjeppe** [tcplugins/tcWebHooks#55]
Using the property ${buildStatusHtml} as webhook.body when using Tailored JSON mode (e.g. {“text”:”${buildStatusHtml}”}) will produce a malformed JSON object, since the ${buildStatusHtml} property is not escaped.

**Comment by netwolfuk** [comment]
Hi @sirjeppe. Here are a few options in order of (my) preference.

1. Since you are using a 1.1 version, create a template containing your preferred content. This would then be available for all webhooks. This requires editing the _BuildServer/config/webhook-templates.xml_ file on the teamcity server. See [this example](https://github.com/tcplugins/tcWebHooks/blob/custom-templates-with-rest-api/tcwebhooks-core/src/test/resources/webhook-templates-flowdock-example.xml) which uses the [predefined variables](https://netwolfuk.wordpress.com/2013/08/31/custom-templates-and-branches-in-tcwebhooks/) the plugin provides. 
1. Build an equivalent string in the webhook.body yourself utilising the [predefined variables](https://netwolfuk.wordpress.com/2013/08/31/custom-templates-and-branches-in-tcwebhooks/) the plugin provides. This can be done by editing the webhook.body build parameter in the teamcity UI.
1. Define your own [custom buildStatusHtml](https://github.com/tcplugins/tcWebHooks/wiki/Customising-the-buildStatusHtml-Message) (or define another one like buildStatusJson). This requires editing a file on the server to customise each webhook after you create it.
1. I add a buildStatusJson variable and release a new version of the plugin.

**Comment by sirjeppe** [comment]
Cool! Thank you for the quick reply :) I think any of the first three will be possible to do, so I will go ahead and implement one of them :) So - big thank you for giving me those workaround hints!

However - in the end, ${buildStatusHtml} will never be possible to use with the Tailored JSON format unless escaped when reading it out since it will not produce a valid JSON string otherwise, so IMHO you should escape it, if the intention is to be able to produce a customized JSON-encoded string using it :)

I would prefer escaping buildStatusHtml in Tailored JSON mode before adding an additional (escaped) version called buildStatusJson, since I assume any (and all) properties from the original JSON object are meant to be able to used in Tailored JSON mode?

**Comment by netwolfuk** [comment]
> I assume any (and all) properties from the original JSON object are meant to be able to used in Tailored JSON mode?

Tailored JSON simply echoes the string into the webhook, and expects the input to be already valid JSON. So I suspect any of the variables which contain JSON special characters will fail.

However, I just remembered I added an escaping method a while ago. I'm not sure if it's in a released version, but you could try setting webhook.body to: ```${escapejson(buildStatusHtml)}```. 

I'm trying to remember why I added it, because it doesn't quite produce the result I was expecting for the buildStatusHtml string. However, you might find that it's useful as part of option 2 or 3, in case you need to escape one of the parts of the message you build up. I'd need to double check if it's used in option 1.

**Comment by sirjeppe** [comment]
Yey! That worked like a charm! Awesome :) Problem solved! Then users have full control over when they need JSON encoding.

**Comment by netwolfuk** [comment]
Great, thanks for the feedback.
