### ISSUE TITLE
Secure build properties are included as plain text

### ISSUE THREAD

**Issue by mbcrawfo** [tcplugins/tcWebHooks#74]
This is a pretty significant security issue, IMO... any secure properties/passwords in the build configuration are included in the POST body as plain text.  Secure properties really should be obscured as they are in the TeamCity API.  If you feel webhooks absolutely needs to support this, passwords should be obscured by default, unless an admin enables the plain text password "feature" in the plugin config.

**Comment by netwolfuk** [comment]
Yes. the information included in a webhook POST has slowly expanded over the years.
At the moment, the object used to provide values for `${variables}` is the same as the one serialised as part of the webhook. And it's now leaking way too much info.

That is why the old formats are deprecated in the version 1.1 alphas with the preference being to build a template of the exact payload you want, and use that with webhooks as the payload. I am developing the UI for template editing, it's just slow going at the moment due to new baby and new job. You can already define your own templates by editing `~/.BuildServer/config/webhook-templates.xml`. See [here](https://github.com/tcplugins/tcWebHooks/blob/1.1.x.x/tcwebhooks-core/src/test/resources/webhook-templates-flowdock-example.xml) for examples.

Hiding passwords is complicated, as when I get the items, they are just strings. I guess I could iterate over the key names, and if they happen to contain "password" then mask them, but that seems unlikely to catch everything. This is a blacklisting approach.

I have been thinking about adding "light" versions of the deprecated payload formats (JSON, XML, NVPAIRS) where only items defined as parameters are sent in the POST payload. This is more of a whitelisting approach.
These are the parameters provided to the build [as parameters named `webhook.*`](https://netwolfuk.wordpress.com/2014/09/22/building-tcwebhooks-custom-parameters-from-teamcity-build-parameters/) or defined in the [webhook config XML](https://github.com/tcplugins/tcWebHooks/blob/1.1.x.x/tcwebhooks-core/src/test/resources/project-settings-test-all-states-enabled-with-branchNameFilter.xml#L20-L23) as parameters.

Would the templates approach work for you? Or would "light" versions work better? Or neither?

**Comment by netwolfuk** [comment]
I just checked. On linux, the payload includes environment variables for the shell under which the build is running (presumably the shell that started the agent), and I don't have any shell variables containing passwords except the one that teamcity sets. That one is masked out already.

```
      {
        "name": "system.teamcity.auth.password",
        "value": "*******"
      },
```

**Comment by mbcrawfo** [comment]
It looks like all of the password properties being returned have the name prefixed with "secure:teamcity.password.", e.g. secure:teamcity.password.AWS-Secret-Key.  So maybe that can be used as a filter to mask out values?  This is on TC 2017.3 running on windows server.

This isn't a huge concern for me personally since (at the moment anyway) we are only interested in posting locally to a service running on the TC server.  At the least though it would be nice to see some clear warnings in the documentation until the default templates are fully deprecated.

**Comment by mbcrawfo** [comment]
It looks like this is actually fixed in the latest 1.1-alpha10.157.147 version.

**Comment by netwolfuk** [comment]
I don't remember making a change like that. Did you also update TeamCity?

**Comment by mbcrawfo** [comment]
No, not since posting the issue.

So, this is interesting.  Before I was just looking at the build started event, but now I'm using the success/failed events with a custom template.  I just ran a build with everything turned on and looked at all of the outputs using the legacy json...

Build started and changes loaded both include the raw password strings.  I also noticed that parameter values aren't fully processed(?) in them.  For example, our `vcsroot.url` includes some %20's that have to be escaped as %%20, and these two events return the raw string entered in the web UI.  The before build finished and build finished events both include obscured password strings, and the vcs root url has been processed to remove the escaping.

I would hazard a guess that TeamCity must be processing or finalizing the parameters sometime after the changes are loaded but before the build runners start.  If your goal is to eventually have everyone make their own templates, I think it's probably not an issue.  Project admins can gain access to passwords anyway, so they can choose to include them in webhooks at their own risk...
