### ISSUE TITLE
Predefined templates for services

### ISSUE THREAD

**Issue by elovelan** [tcplugins/tcWebHooks#8]
This is an awesome idea for an enhancement. Breaking it out into its own issue since I'd like to work on it and so it can be discussed separately.

From #3:

> I'm also wondering about having some prefined global templates for common services like HipChat, Stack, FlowDock, etc so that users can pick them from a list when creating a webhook. I'm still mulling over in my mind about what the "payload customisation" (aka custom template) UI would look like. I imagine it will probably be another tab in the webhook edit screen.

**Comment by netwolfuk** [comment]
Great timing! I've actually started working on this and have created a new branch called custom-templates. Here are my thoughts so far.

- [x] WebHookTemplateManager spring Controller for managing templates.<br>
       All templates will register themselves and exist in here. 
- [x] Example Template coded in Java and wired into spring config. <br>
       See SlackComWebHookTemplate.java TODO: write actual templates.
- [ ] Example loading of template from XML config.  - *partially done* <br>
See: WebHookTemplateJaxHelperTest and WebHookTemplateFromXml <br>
I'm unsure yet as to whether that XML snippet should reside in the
teamcity main xml config file (auto-reloading) or in its own xml config file (need to figure out how to get teamcity to watch that file).<br>
Also, not sure I've completely arrived at the final model for that: <br>
Can a template-text be shared across multiple buildstates? <br>
Currently only supports a default or one listed for each type. See webhook-templates.xml as current anticipated config format.
- [ ] Get XML declared templates to register themselves with WebHookTemplateManager. <br>
This needs a bit more thought: eg.<br>
Templates with the same name as a spring one will overwrite? Or suppliment the settings? <br>
What about declaring templates at the project level rather than in main-config.xml? <br>
Project templates are inherited from parent projects? <br>
Do subprojects with same template name enhance or overwrite existing templates?
- [ ] Ajax handler to get list of relevant templates for webhook. <br>
Should check if all selected build states are supported (eg, fininshed, fixed, broken, failed, successful). 
- [ ] WebUI - Do ajax call to get list of relevant templates for payload type (xml, json, tailoredjson, etc) and buildStates selected (starting, finished, successful, etc).
- [ ] WebUI - Allow use of existing templates, or build one's own. <br>I wanted to do drag and drop into template editor, but that seems really brittle from the javascript libraries I can find. Maybe just clicking a variable to insert it into the edit area at the current cursor location is ok for a first go. Drag and drop of existing template variables inside the edit area would be nice, but our audience can probably handle cut and paste.
- [ ] WebUI - Ajax call to parse and build expected payload based on most recent build in project<br>
This is the big win. One can see what one's template output looks like in the window as one edits the template. With actual values inserted and rendered in the template. <br>
Should use subproject if no builds at that project level, most recent build for that buildType if one is creating a webhook for a specific build or set of builds. 
- [ ] Admin WebUI - For editing global templates.

**More stuff I'm mulling over**
I have some very definite ideas about UI look and feel. I'll mock those up in balsamic on my work laptop and add them to this ticket.

**Comment by netwolfuk** [comment]
Here is my current thinking for UI
Instead of changing the format, you just pick a template, which already knows its preferred format.
There would be an option for "JSON with custom template", etc.
![webhookconfig_url](https://cloud.githubusercontent.com/assets/88687/8849994/7b767998-3198-11e5-9bea-ea9c92adc747.png)

You can view any template (and its results) and even edit a local copy of the content if you want.
![webhookconfig_messagecontent](https://cloud.githubusercontent.com/assets/88687/8850004/82ce504e-3198-11e5-8185-4acac849e525.png)

**Comment by netwolfuk** [comment]
Note to self. Template failures should fail build. eg, Template can't be be built because of:
- error loading template
- resolving build event to the template's supported events.
- error doing variable transposing.

Should be controlled by global setting: <template-failures-should-fail-build enabled="true" />

Also, would be nice to edit admin settings in admin page now that there is an extension point in teamcity's admin screen.

**Comment by netwolfuk** [comment]
A very first cut of the templating is available. Templates can be written in java, or added to the XML file. See https://github.com/tcplugins/tcWebHooks/releases/tag/v1.1-alpha1.39.83
Templates can NOT be edited in the UI yet.
This version is available mainly to test that backwards compatibility of the old formats is not broken.

**Comment by netwolfuk** [comment]
A new version of the template based plugin is available. Now with an ElasticSearch template and formatted dates.
If you want to POST to elastic search in a date based index (eg, /teamcity-2015-09/buildevent), choose Elastic Search as the payload format and enter a URL that looks similar to this: http://172.16.1.61:9200/teamcity-${now(yyyy-MM)}/buildevent
Download the playing from here: https://github.com/tcplugins/tcWebHooks/releases/tag/v1.1-alpha2.41.86

Note: Actual templates are not editable in the UI yet.

**Comment by netwolfuk** [comment]
This work is now represented by #67
