### ISSUE TITLE
Templates will not save

### ISSUE THREAD

**Issue by schancel** [tcplugins/tcWebHooks#90]
## Expected Behavior
Should be able to save the template

## Current Behavior
<img width="429" alt="image" src="https://user-images.githubusercontent.com/213740/34846403-ea552656-f6cc-11e7-9087-5cad29b9927a.png">

Click "save template" nothing happens

## Steps to Reproduce (for bugs)
Install the plugin in teamcity 10, try to make a template

## Your Environment
* tcWebHooks Version: latest
* TeamCity Version: 10.0
* TeamCity server Operating System: MacOS X
* Are you using a WebHook Template?: Trying to

**Comment by netwolfuk** [comment]
Can you walk through the steps?
- eg, did you create a new template from scratch or, copy an existing one?

Is there anything useful in the Javascript console?
Which browser are you using?

**Comment by schancel** [comment]
I'm using Firefox.  I clicked `/webhooks/templates.html` I clicked the link at the bottom of the page to create a new template.  I'll have to setup the environment again as I had torn it down.  Is there a real time way we could chat?

**Comment by netwolfuk** [comment]
Yeah. I have created a gitter, https://gitter.im/tcplugins/tcWebHooks

**Comment by netwolfuk** [comment]
The issue ended up being that navigating to /webhooks/template.html with no templateId or an invalid one does not inform the user of this, and appears to work (sort of).

The fix is to add a link back to the templates list if `myTemplateManager.getTemplateConfig()` returns null.

The following has been implemented.

![image](https://user-images.githubusercontent.com/88687/34901209-2675e5f8-f86c-11e7-8721-a7070c108f31.png)
