### ISSUE TITLE
Changes variable does not serialize to Json

### ISSUE THREAD

**Issue by opm99** [tcplugins/tcWebHooks#98]
## Expected Behavior
When template contains configuration:
```
// other json ..
"changes": ${changes}
```

Payload would contain fields related to the VCS changes that triggered the build (shown in https://github.com/tcplugins/tcWebHooks/wiki/Example-Webhook-Output---JSON)
## Current Behavior
Changes variable does not serialize to Json
```
"changes": "[webhook.teamcity.payload.content.WebHooksChanges@7e8231]"
```

## Steps to Reproduce (for bugs)

1. Create a template through UI
2. Add following json to a Build event template (for build finished/started)
```
{
	"build": {
		"buildTypeId": "${buildTypeId}",
		"buildId": "${teamcity.build.id}",
	},
	"changes": "${changes}"
}
```
3. Set up a webhook for Build started/finished on a TC build that is triggered for a commit
4. Observe data received on Webhook Target URL

## Your Environment

* tcWebHooks Version: 1.1-alpha15.216.313
* TeamCity Version: 2017.2.1
* TeamCity server Operating System: Windows 2012
* Are you using a WebHook Template?: Yes

**Comment by netwolfuk** [comment]
Thanks for finding that. All of the object ones in the model will probably have the same issue.

**Comment by netwolfuk** [comment]
Thinking about this some more, probably all json fields need to be "serialised".
For example, a variable containing and json reserved character will also break the payload. eg, `[]{}"'`

**Comment by netwolfuk** [comment]
I have added support to the `VariableResolver` so that any item that is not `String`, `Integer` or `Boolean` is passed through a JSON parser.  it's in a separate branch, and you're welcome to try a [build from here](https://teamcity.jetbrains.com/viewType.html?buildTypeId=WebHooksAndOtherPlugins_TcWebHooks&branch_WebHooksAndOtherPlugins=issue_98_-_serialise_json&tab=buildTypeStatusDiv). 

However, I've realised that the format is fixed, and not really that useful, unless you can access parts of it. I suppose if you're post processing it on the server side once the webhook is delivered, it might be ok, but if you are wanting to do something smarter with the values inside the template, you need a smarter templating tool.
I have therefore also raised issue #103 so that templates can have more smarts.
